### ISSUE TITLE
`Pkg.add("ConjugatePriors"); using ConjugatePriors` fails during precompilation.

### ISSUE THREAD

**Issue by coventry** [JuliaStats/ConjugatePriors.jl#11] opened 2016-05-29 05:34 UTC
This doesn't happen if I `Pkg.checkout("ConjugatePriors")` before `using`.  Could you please put a version tag on current master so I can pin it?

NB: The same thing happens with julia v0.4.5.  See discussion [here](https://gitter.im/JuliaLang/julia?at=574a16e3da3f93da6f213bd1).

```
user@julia:~/src/cat.jl$ rm -rf ~/.julia
user@julia:~/src/cat.jl$ julia -e 'Pkg.add("ConjugatePriors"); using ConjugatePriors'
INFO: Initializing package repository /home/user/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of ArrayViews from https://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of ConjugatePriors from https://github.com/JuliaStats/ConjugatePriors.jl.git
INFO: Cloning cache of Distributions from https://github.com/JuliaStats/Distributions.jl.git
INFO: Cloning cache of PDMats from https://github.com/JuliaStats/PDMats.jl.git
INFO: Cloning cache of StatsBase from https://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of StatsFuns from https://github.com/JuliaStats/StatsFuns.jl.git
INFO: Installing ArrayViews v0.6.4
INFO: Installing Compat v0.7.20
INFO: Installing ConjugatePriors v0.1.2
INFO: Installing Distributions v0.8.9
INFO: Installing PDMats v0.3.6
INFO: Installing StatsBase v0.8.1
INFO: Installing StatsFuns v0.2.2
INFO: Package database updated

WARNING: deprecated syntax "call(::Type{Base.ByteString}, ...)".
Use "(::Type{Base.ByteString})(...)" instead.

WARNING: deprecated syntax "call(::Type{Base.ByteString}, ...)".
Use "(::Type{Base.ByteString})(...)" instead.

WARNING: deprecated syntax "call(::Type{Base.ByteString}, ...)".
Use "(::Type{Base.ByteString})(...)" instead.

WARNING: deprecated syntax "call(::Type{Base.ByteString}, ...)".
Use "(::Type{Base.ByteString})(...)" instead.

WARNING: deprecated syntax "call(::Type{Base.ByteString}, ...)".
Use "(::Type{Base.ByteString})(...)" instead.

WARNING: deprecated syntax "call(::Type{Base.ByteString}, ...)".
Use "(::Type{Base.ByteString})(...)" instead.
WARNING: `@unix_only` is deprecated, use `@static if is_unix()` instead
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in @unix_only(::Any) at ./deprecated.jl:1226
 in include_from_node1(::String) at ./loading.jl:426
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /home/user/.julia/v0.5/Compat/src/Compat.jl, in expression starting on line 132
WARNING: Method definition (::Type{ArrayViews.UnsafeContiguousView})(Ptr{#T<:Any}, Int64, Tuple{Vararg{Int64, #N<:Any}}) in module ArrayViews at /home/user/.julia/v0.5/ArrayViews/src/arrviews.jl:18 overwritten at /home/user/.julia/v0.5/ArrayViews/src/arrviews.jl:26.
WARNING: Base.SparseMatrix is deprecated.
  likely near /home/user/.julia/v0.5/PDMats/src/chol.jl:9
WARNING: Base.SparseMatrix is deprecated.
  likely near /home/user/.julia/v0.5/PDMats/src/chol.jl:9
WARNING: symbol is deprecated, use Symbol instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in symbol(::String, ::Vararg{String,N}) at ./deprecated.jl:30
 in macro expansion; at /home/user/.julia/v0.5/Distributions/src/univariates.jl:199 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /home/user/.julia/v0.5/Distributions/src/univariates.jl, in expression starting on line 193
WARNING: symbol is deprecated, use Symbol instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in symbol(::String, ::Vararg{String,N}) at ./deprecated.jl:30
 in macro expansion; at /home/user/.julia/v0.5/Distributions/src/univariates.jl:200 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /home/user/.julia/v0.5/Distributions/src/univariates.jl, in expression starting on line 193
WARNING: symbol is deprecated, use Symbol instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in symbol(::String, ::Vararg{String,N}) at ./deprecated.jl:30
 in @_delegate_statsfuns(::Any, ::Any, ::Symbol, ::Vararg{Symbol,N}) at /home/user/.julia/v0.5/Distributions/src/univariates.jl:316
 in include_from_node1(::String) at ./loading.jl:426
 in macro expansion; at /home/user/.julia/v0.5/Distributions/src/univariates.jl:408 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /home/user/.julia/v0.5/Distributions/src/univariate/discrete/binomial.jl, in expression starting on line 71
WARNING: Method definition (::Type{Distributions.MvNormalKnownCov})(#Cov<:PDMats.AbstractPDMat) in module Distributions at /home/user/.julia/v0.5/Distributions/src/multivariate/mvnormal.jl:148 overwritten at /home/user/.julia/v0.5/Distributions/src/multivariate/mvnormal.jl:151.
INFO: Recompiling stale cache file /home/user/.julia/lib/v0.5/Distributions.ji for module Distributions.
WARNING: symbol is deprecated, use Symbol instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in symbol(::String, ::Vararg{String,N}) at ./deprecated.jl:30
 in macro expansion; at /home/user/.julia/v0.5/Distributions/src/univariates.jl:199 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /home/user/.julia/v0.5/Distributions/src/univariates.jl, in expression starting on line 193
WARNING: symbol is deprecated, use Symbol instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in symbol(::String, ::Vararg{String,N}) at ./deprecated.jl:30
 in macro expansion; at /home/user/.julia/v0.5/Distributions/src/univariates.jl:200 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /home/user/.julia/v0.5/Distributions/src/univariates.jl, in expression starting on line 193
WARNING: symbol is deprecated, use Symbol instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in symbol(::String, ::Vararg{String,N}) at ./deprecated.jl:30
 in @_delegate_statsfuns(::Any, ::Any, ::Symbol, ::Vararg{Symbol,N}) at /home/user/.julia/v0.5/Distributions/src/univariates.jl:316
 in include_from_node1(::String) at ./loading.jl:426
 in macro expansion; at /home/user/.julia/v0.5/Distributions/src/univariates.jl:408 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /home/user/.julia/v0.5/Distributions/src/univariate/discrete/binomial.jl, in expression starting on line 71
WARNING: Method definition (::Type{Distributions.MvNormalKnownCov})(#Cov<:PDMats.AbstractPDMat) in module Distributions at /home/user/.julia/v0.5/Distributions/src/multivariate/mvnormal.jl:148 overwritten at /home/user/.julia/v0.5/Distributions/src/multivariate/mvnormal.jl:151.
WARNING: Module PDMats uuid did not match cache file
  This is likely because module PDMats does not support  precompilation but is imported by a module that does.
ERROR: LoadError: __precompile__(true) but require failed to create a precompiled cache file
 in require(::Symbol) at ./loading.jl:366
 in include_from_node1(::String) at ./loading.jl:426
 in eval(::Module, ::Any) at ./boot.jl:225
 in require(::Symbol) at ./loading.jl:357
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /home/user/.julia/v0.5/ConjugatePriors/src/ConjugatePriors.jl, in expression starting on line 5
user@julia:~/src/cat.jl$ 
```

**Comment by kmsquire** [comment] 2016-05-29 06:32
Works for me.  Can you give the output of `Pkg.status()`?

**Comment by alxempirical** [comment] 2016-05-29 15:23
@kmsquire, did you move `~/.julia` out of the way first? 

Here is a Dockerfile which reproduces:

```Dockerfile
FROM julia
RUN julia -e 'Pkg.add("ConjugatePriors"); using ConjugatePriors' || julia -e 'Pkg.status()'
```

Here is example output:

```
Sending build context to Docker daemon 40.21 MB
Step 1 : FROM julia
 ---> 6d3598a3c2c2
Step 2 : RUN julia -e 'Pkg.add("ConjugatePriors"); using ConjugatePriors' || julia -e 'Pkg.status()'
 ---> Running in aa710237e638
INFO: Initializing package repository /root/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of ConjugatePriors from git://github.com/JuliaStats/ConjugatePriors.jl.git
INFO: Cloning cache of Distributions from git://github.com/JuliaStats/Distributions.jl.git
INFO: Cloning cache of PDMats from git://github.com/JuliaStats/PDMats.jl.git
INFO: Cloning cache of StatsBase from git://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of StatsFuns from git://github.com/JuliaStats/StatsFuns.jl.git
INFO: Installing ArrayViews v0.6.4
INFO: Installing Compat v0.7.20
INFO: Installing ConjugatePriors v0.1.2
INFO: Installing Distributions v0.8.9
INFO: Installing PDMats v0.3.6
INFO: Installing StatsBase v0.8.1
INFO: Installing StatsFuns v0.2.2
INFO: Package database updated
INFO: Recompiling stale cache file /root/.julia/lib/v0.4/Distributions.ji for module Distributions.
WARNING: Module PDMats uuid did not match cache file
  This is likely because module PDMats does not support  precompilation but is imported by a module that does.
ERROR: LoadError: __precompile__(true) but require failed to create a precompiled cache file
 in require at ./loading.jl:268
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in require at ./loading.jl:259
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /root/.julia/v0.4/ConjugatePriors/src/ConjugatePriors.jl, in expression starting on line 5
1 required packages:
 - ConjugatePriors               0.1.2
6 additional packages:
 - ArrayViews                    0.6.4
 - Compat                        0.7.20
 - Distributions                 0.8.9
 - PDMats                        0.3.6
 - StatsBase                     0.8.1
 - StatsFuns                     0.2.2
 ---> 3d03c9095c73
Removing intermediate container aa710237e638
Successfully built 3d03c9095c73
```

**Comment by kmsquire** [comment] 2016-05-29 18:56
Okay, I get the same error when I check out on a clean `.julia`.  But tagging a new version isn't going to help, because I get the same error when I do:

```julia
Pkg.add("ConjugatePriors")
Pkg.checkout("ConjugatePriors")
using ConjugatePriors
```

The error about the `PDMats` uuid not matching is probably a bug in Julia, because, e.g., I can do the following with no problem (from a clean `.julia`).

```
Pkg.add("Distributions")
Pkg.add("PDMats")
import Distributions
import PDMats
workspace()
Pkg.add("ConjugatePriors")
using ConjugatePriors
```

(Output is messy, so posting here: https://gist.github.com/kmsquire/7504194e7c19b7b1709c561b4e12c2dd)

This would also probably be fixed by removing the upper bound on the required version of `PDMats`, although that wouldn't fix the julia bug.  

See #9 and #10.

I don't have time to test more right now, but will try to look again later, and hopefully post a bug report in Julia.

Cc: @stevengj, who might have some ideas about the uuid problem.

**Comment by alxempirical** [comment] 2016-05-29 19:26
Thanks.  I'd just come over here to say that I'd just found `Pkg.add("ConjugatePriors"); Pkg.test("ConjugatePriors")` seems to work, too, and noticed your message.

> This would also probably be fixed by removing the upper bound on the required version of PDMats, although that wouldn't fix the julia bug.

I'm not sure.  At the least you have to free up the `Distributions` pin as well, because the `REQUIRE'd one [also requires PDMats v0.3.2](https://github.com/JuliaStats/Distributions.jl/blob/v0.8.9/REQUIRE#L3)`.

I've been trying to get the latest `master` versions of `Distributions` and `ConjugatePriors` to play nice for a few hours.  The `Dockerfile` at the bottom of this message tries to fix the `ConjugatePriors` `PDMats` version to be in line with the one in `Distributions`, but fails with `MethodError: no method matching _rand!(::Distributions.MvNormalCanon{PDMats.PDMat{Float64,Array{Float64,2}},Array{Float64,1}}, ::Array{Float64,1})` on [line 52 of `conjugates_mvnormal.jl`](https://github.com/JuliaStats/ConjugatePriors.jl/blob/master/test/conjugates_mvnormal.jl#L52).

I've reduced the failure to the following minimal case, which the `Dockerfile` references as `conjugates_mvnormal.jl`.  Output of the `println` is `Tuple{Tuple{Distributions.MvNormal{PDMats.PDMat{Float64,Array{Float64,2}},Array{Float64,1}},Array{Float64,2}},DataType,Array{Float64,2}}`.

```julia
# Conjugate models for multivariate normal

using Distributions
using ConjugatePriors
using Base.Test

import ConjugatePriors: posterior, posterior_randmodel  # One-line change

# Posterior
n = 100
mu_true = [2., 3.]
Sig_true = eye(2)
Sig_true[1,2] = Sig_true[2,1] = 0.25
mu0 = [2.5, 2.5]
Sig0 = eye(2)
Sig0[1,2] = Sig0[2,1] = 0.5
X = rand(MultivariateNormal(mu_true, Sig_true), n)

pri = MultivariateNormal(mu0, Sig0)

println(typeof(((pri, Sig_true), MvNormal, X)))
ps = posterior_randmodel((pri, Sig_true), MvNormal, X)
```

```Dockerfile
FROM ubuntu:14.04

# Get wget
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get install -y --no-install-recommends wget

# Install Julia nightly build
RUN wget -O julia.tgz --no-check-certificate -q \
         https://status.julialang.org/download/linux-x86_64
RUN tar xf julia.tgz && mv julia-* julia
ENV JULIABIN=julia/bin/julia

# Get git
RUN apt-get install -y --no-install-recommends git

# Get the latest ConjugatePriors.jl
RUN $JULIABIN -e 'Pkg.add("ConjugatePriors"); Pkg.checkout("ConjugatePriors")'

# Change ConjugatePriors.jl's PDMats dependency so it's in line with current
# Distributions.jl's.
RUN sed -i s'/PDMats .*/PDMats 0.4/'g '/root/.julia/v0.5/ConjugatePriors/REQUIRE'

# Get the latest Distributions.jl
RUN $JULIABIN -e 'Pkg.checkout("Distributions")'

# Force compilation of ConjugatePriors and dependencies
RUN $JULIABIN -e 'using ConjugatePriors'

COPY conjugates_mvnormal.jl /

RUN echo "Cache buster 1"
RUN $JULIABIN conjugates_mvnormal.jl
RUN $JULIABIN '/root/.julia/v0.5/ConjugatePriors/test/runtests.jl'
```

**Comment by tawheeler** [comment] 2016-09-12 21:59
The problem is that Distributions.jl v10.2 has

```
_rand!(d::MvNormalCanon, x::AbstractMatrix) = add!(unwhiten_winv!(d.J, randn!(x)), d.μ)
```

instead of

```
_rand!(d::MvNormalCanon, x::AbstractVecOrMat) = add!(unwhiten_winv!(d.J, randn!(x)), d.μ)
```

I submitted an issue there.

**Comment by ararslan** [comment] 2017-06-30 07:05
Should be good now.

**Closed by ararslan** 2017-06-30 07:05 UTC
